### PR TITLE
Prime Client Window - more tests

### PR DESCRIPTION
**Pull request by christophs78**
@tandraschko : #testRenderedUrls fails together with MyFaces used for integration-tests.
My current feeling is, that this may be related to the combination of MyFaces and PrimeFaces.

Mojarra does following as part of `com.sun.faces.context.UrlBuilder#appendQueryString`:
```
if (appendClientWindow && -1 == url.indexOf(ResponseStateManager.CLIENT_WINDOW_URL_PARAM)) {
	if (null != cw) {
		String clientWindow = cw.getId();
		if (!hasQueryString) {
			url.append(QUERY_STRING_SEPARATOR);
		} else {
			url.append(PARAMETER_PAIR_SEPARATOR);
		}
		url.append(ResponseStateManager.CLIENT_WINDOW_URL_PARAM).append(PARAMETER_NAME_VALUE_SEPARATOR).append(clientWindow);
```

Can´t find similar code when i debug MyFaces.

### CODE REVIEW

**Comment by melloware** [comment]
@christophs78 Are you sure Mojarra is not doing it wrong?  I opened this ticket at Mojarra: https://github.com/eclipse-ee4j/mojarra/issues/4727

**Comment by christophs78** [comment]
Think Thomas did https://github.com/primefaces/primefaces/commit/c4b63bd6b6501bdd2e63cccccebfde106c9269c5 to fix this for Mojarra.

And:
https://github.com/primefaces/primefaces/issues/6030#issuecomment-648085175

Thought our integration-tests already uses a MyFaces-version where this should be fixed. But maybe incomplete.

**Comment by tandraschko** [comment]
@christophs78 can you give me a primefaces-test and steps to reproduce?
And please make sure you use 2.3.7

**Comment by christophs78** [comment]
Hm. https://github.com/apache/myfaces/commit/534119109af4e51052cea252b311f6485f5e8273
Fixed for MyFaces 2.3.7 but TomEE 8.0.5 comes with MyFaces 2.3.6. https://github.com/apache/tomee/blob/tomee-8.0.5/pom.xml#L196

**Comment by tandraschko** [comment]
yeah, my PR for 2.3.7 was merged after the 8.0.5 release.
But you can upgrade MF via exclusions/dependencies, ping me if you need help

**Comment by christophs78** [comment]
Personally i´m a gradle-guy - so i would appreciate your help  with the maven-based MF-upgrade.

**Comment by tandraschko** [comment]
something like this should work (untested):
https://gist.github.com/tandraschko/06f2123876edcb9dd491c9782a73c165

**Comment by christophs78** [comment]
> something like this should work (untested):
> https://gist.github.com/tandraschko/06f2123876edcb9dd491c9782a73c165

Works. Thank you!

**Pull request merged**
