### PR TITLE
DataTable003Test try more things to fix this for JDK11/Chrome on Travis CI

### PR DESCRIPTION
**Pull request by christophs78**

### CODE REVIEW

**Comment by christophs78** [comment]
After adding some more debug-output all tests passed two times. Kind of weird.
It feels a bit like i only removed the symptoms but not the root cause.
On my dev-notebook i had not been able to reproduce this issue with Chrome.

@phillipross : Do you have some in-depth Selenium-knowledge? When yes - can you please also look at https://github.com/primefaces-extensions/primefaces-integration-tests/pull/20?
It feels a bit like a timing issue. Is there a clean way to solve this?

**Comment by melloware** [comment]
Since sorting is an AJAX request I think you might have to do something like InputText does using Guard Ajax.
```java
PrimeSelenium.guardAjax(input).sendKeys(Keys.TAB);
```

**Comment by christophs78** [comment]
Does not work for
`actions.keyDown(Keys.META).click(PrimeSelenium.guardAjax(eltSortName)).keyUp(Keys.META).perform();`

```
Caused by: org.openqa.selenium.TimeoutException: Timeout while waiting for AJAX complete!
	at org.primefaces.extensions.selenium.internal.Guard.lambda$ajax$3(Guard.java:88)
	at net.bytebuddy.renamed.java.lang.Object$ByteBuddy$LYJlSoMI.getWrappedElement(Unknown Source)
	at org.openqa.selenium.interactions.PointerInput$Origin.asArg(PointerInput.java:204)
	at org.openqa.selenium.interactions.PointerInput$Move.encode(PointerInput.java:155)
	at org.openqa.selenium.interactions.Sequence.encode(Sequence.java:75)
	at org.openqa.selenium.interactions.Sequence.toJson(Sequence.java:84)
	... 96 more
```

@tandraschko: Can you please provide some insight what PrimeSelenium.guardAjax does and for which usecases it´s intended. (Maybe we should add some JavaDoc. Looked at the Source and not totally sure wether it fit´s for this usecase.)

**Comment by melloware** [comment]
Hmm I would think you would need to guard the `click` since that triggers it right?

**Comment by christophs78** [comment]
Yes, i understand your idea. 

But...
-  i´m not able to figure out a way to combine `PrimeSelenium.guardAjax` with `org.openqa.selenium.interactions.Actions`. (Actions seems to be the only way to hold META-key during clicking a `WebElement`)
- even if we find a way to combine this i´m not totally sure weather that´s the way to go

At this point i hoped we may get some background from Thomas who implemented `PrimeSelenium.guardAjax` or from Phillip who seems to have some serious Selenium-background.

**Comment by christophs78** [comment]
```
Action actionMetaPlusSortClick = actions.keyDown(Keys.META).click(PrimeSelenium.guardAjax(eltSortName)).keyUp(Keys.META).build();
PrimeSelenium.guardAjax(actionMetaPlusSortClick).perform();
```

also results in 
```
Caused by: org.openqa.selenium.TimeoutException: Timeout while waiting for AJAX complete!
	at org.primefaces.extensions.selenium.internal.Guard.lambda$ajax$3(Guard.java:88)
	at net.bytebuddy.renamed.java.lang.Object$ByteBuddy$eNG1VG64.getWrappedElement(Unknown Source)
	at org.openqa.selenium.interactions.PointerInput$Origin.asArg(PointerInput.java:204)
	at org.openqa.selenium.interactions.PointerInput$Move.encode(PointerInput.java:155)
	at org.openqa.selenium.interactions.Sequence.encode(Sequence.java:75)
	at org.openqa.selenium.interactions.Sequence.toJson(Sequence.java:84)
	... 101 more
```

**Comment by christophs78** [comment]
Look´s like we have a way how this works stable on Travis CI with Chrome. (And hope this is not only because Travis CI today has some minimal different runtime-behaviour which results in timing-differences.)

**Comment by melloware** [comment]
Nice work!

**Pull request merged**
