### PR TITLE
https://github.com/primefaces/primefaces/issues/7271

### PR DESCRIPTION
**Pull request by christophs78**

### CODE REVIEW

**Comment by christophs78** [comment]
@melloware : Maybe you can check this on your MacOS-device. I don´t think InputNumber is totally broken on Safari. (Showcase looks OK my iPad.) But something weird is going on.

**Comment by melloware** [comment]
Good idea let me check this one out.

**Comment by melloware** [comment]
OK this rings a bell and I think its why i switched all the other test to use `setValue` because Safari is a little whacky with keyboard input and JavaScript firing on every press like InputNumber does.

**Comment by christophs78** [comment]
`setValue` does not work for this integration test, because we can´t reproduce the original issue in this way. So i disabled this integration test for Safari.

**Comment by melloware** [comment]
That is a good idea because its still a valuable test!

**Pull request merged**
