### PR TITLE
Datatable: SelectOneMenu has wrong value after filtering

### PR DESCRIPTION
**Pull request by christophs78**
this test currently fails due to a regression introduced by https://github.com/primefaces/primefaces/commit/89972adc0ce27294ec36bf454b153005cc2b753e

### CODE REVIEW

**Comment by melloware** [comment]
This test is failing and I am not sure its checking the right thing?  We should be checking that the SelectOne values in the datatable rows retain their value not that the filter retains its value right?

**Comment by melloware** [comment]
Steps would be..

1. Check the value of SelectOne in Row 1.
2. Change the value of SelectOne in Row 1 to something else.
3. Now Filter to make sure NO ROWS come back in the filter like filtering on Programming Language "XXX".
4. Remove the filter so the rows appear again.
5. Check the SelectOne of Row 1 and make sure it still has the value set in Step 2 and not its original value.

**Comment by christophs78** [comment]
Ok, maybe i should rename the test i added yesterday. IMO it test´s things that should work but as you say probably not what https://github.com/primefaces/primefaces/issues/7026 exactly reports. The test introduced yesterday breaks because filteredValue is currently broken.
I´ll try to add another test which does the steps you described above.

**Comment by christophs78** [comment]
@melloware: Side-question regarding both DataTable009 - tests:
Is `<p:ajax event="filter"` executed before or after the filter is applied?
Until @Rapster´s modification a few days ago it was something like "afterFilter", now it´s "beforeFilter". Rapster moved some code within FilterFeature from decode to encode. This explains this behaviour-change.
When i look into https://github.com/primefaces/primefaces/issues/1390 it sounds like some time ago "filter" was a "beforeFilter". 
What is the correct behaviour? --> The behaviour we should test and the behaviour we should write into our documentation. Currently i believe it should be "beforeFilter" and we should modify DataTable009 - tests which only worked for some time because "filter" behaved only temporarily during PF10-development like "afterFilter".

**Comment by melloware** [comment]
That is a good question.  I think it was always fired Before filtering.  But there was a ticket if I remember saying it should be after.

**Comment by Rapster** [comment]
From what I can see doing a quick google search, most users expect a "afterFilter" to do some post processing. My guess is that, it used to be a beforeFilter, and users were probably expected to use PostFilterEvent system event to do a afterFilter. But TBH, using a SystemEventClass for this use case sounds like a dirty trick, and considering https://github.com/primefaces/primefaces/issues/1390 I'm not sure it really worked...

Anyway, I might have found a solution/workaround (not sure yet) to fix https://github.com/primefaces/primefaces/issues/7026, revert what my last commit and enable rowStatePreserved will keep select components state saved

**Pull request merged**
