### PR TITLE
GitHub Actions - now it works

### PR DESCRIPTION
**Pull request by christophs78**
image

... and it´s faster than Travis CI :-)
And (at least for now) it seems to be more stable than Travis CI.
Maybe we should move PrimeFaces and PrimeFaces Selenium to Github Actions too.

We need to update readme.md regarding alternate webdriver-directories.

### CODE REVIEW

**Comment by christophs78** [comment]
@melloware: When you are happy with this we may remove Travis CI afterwards. I´ll hope you know how to re-configure Checks-Feature. So it uses Github Actions instead of Travis CI to show wheather the build is fine or not.

**Comment by melloware** [comment]
Let me look into that!  I will get back to you.

**Comment by melloware** [comment]
I removed all the TRAVIS stuff and updated our build badge.

**Comment by christophs78** [comment]
Looks good. Thank you!
I´ll provide PR´s to move PrimeFaces Selenium and PrimeFaces from Travis CI to Github Actions too.

**Comment by melloware** [comment]
Can you also do PrimeFaces Extensions while you are at it?  That would be a huge help!

**Comment by christophs78** [comment]
> Can you also do PrimeFaces Extensions while you are at it? That would be a huge help!

Yes, i´ll look at this.

**Comment by christophs78** [comment]
Sonar-Cloud-Github-Action: https://github.com/SonarSource/sonarcloud-github-action

**Comment by melloware** [comment]
@christophs78 I will do PF Extensions if you do Selenium.  This will be a good learning experience for me.

**Pull request merged**
