### PR TITLE
Safari hacking

### PR DESCRIPTION
**Pull request by christophs78**

### CODE REVIEW

**Comment by christophs78** [comment]
Using `runs-on: macos-11.0` does not seem to be a good idea because somehow limited Github Actions resources. We need to wait and wait until our jobs are executed.

**Comment by christophs78** [comment]
I´ll continue my work this weekend.

**Comment by melloware** [comment]
I was able to remove TestUtil.pause entirely and everything is still passing.  I think your fixes in PrimeSelenium for 100ms wait after JS execution are what fixed everything.  Nice work!

**Comment by christophs78** [comment]
Happy to hear this!
Happy to hear this! Hope this really fixes our issues permanently...

**Pull request closed without merging**
