### PR TITLE
nova-light and saga-themes

### PR DESCRIPTION
**Pull request by christophs78**
Not the most important thing, but should not do harm. ;-)

### CODE REVIEW

**Review by melloware — APPROVED** [review]
Agreed this is a good change.  CSS issues are tough to detect with Selenium but at least this might tell us if something is wholesale broken.

**Comment by melloware** [comment]
Actually to prevent a whole nother build maybe we should make the profiles..

Java8, Chrome, Nova Light
Java8, Firefox, Nova Light

Java11, Chrome, Saga
Java11, Firefox, Saga,

CSP

**Comment by christophs78** [comment]
> Actually to prevent a whole nother build maybe we should make the profiles..
> 
> Java8, Chrome, Nova Light
> Java8, Firefox, Nova Light
> 
> Java11, Chrome, Saga
> Java11, Firefox, Saga,
> 
> CSP

Yes, thought about this too. Just need to figure out how to do this with build.yaml.

**Comment by melloware** [comment]
Let me take a look

**Comment by melloware** [comment]
OK not great but I got the builds down from 8 to 6.

basically I use Saga theme except the CSP profile I use the Nova Light theme.  So it combines CSP and Nova Light.  I figured that was OK because we are testing CSP more than we are testing the theme.

**Pull request merged**
