### PR TITLE
#83 run integration-tests against myfaces and mojarra (JSF 2.3)

### PR DESCRIPTION
**Pull request by christophs78**

### CODE REVIEW

**Comment by christophs78** [comment]
Looks like we have a bunch of issues when running on Mojarra.
Same on my dev-notebook:
image

**Comment by christophs78** [comment]
@tandraschko: With MyFaces 2.3-next-M5 our integration-test won´t even start due to
```
SEVERE: Exception sending context destroyed event to listener instance of class [org.apache.myfaces.webapp.StartupServletContextListener]
java.lang.UnsupportedOperationException: Section 4.4 of the Servlet 3.0 specification does not permit this method to be called from a ServletContextListener that was not defined in web.xml, a web-fragment.xml file nor annotated with @WebListener
	at org.apache.catalina.core.StandardContext$NoPluggabilityServletContext.getServletRegistrations(StandardContext.java:6611)
	at org.apache.myfaces.application.FacesServletMappingUtils.getServletRegistrations(FacesServletMappingUtils.java:121)
	at org.apache.myfaces.application.FacesServletMappingUtils.getFacesServletRegistration(FacesServletMappingUtils.java:152)
	at org.apache.myfaces.webapp.AbstractFacesInitializer.destroyFaces(AbstractFacesInitializer.java:319)
	at org.apache.myfaces.webapp.StartupServletContextListener.contextDestroyed(StartupServletContextListener.java:120)
	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4760)
```

**Comment by tandraschko** [comment]
@christophs78 checking and fixing this now

**Comment by tandraschko** [comment]
@christophs78 can you try a snapshot again?

**Comment by christophs78** [comment]
> @christophs78 can you try a snapshot again?

MyFaces 2.3-next-snapshot?

**Comment by tandraschko** [comment]
yup, you probably have to build it from source first
just commited it 15 mins ago

**Comment by christophs78** [comment]
> yup, you probably have to build it from source first
> just commited it 15 mins ago

Still the same issue. (Took some time because i accidentally tried to compile MyFaces with java 16 and wondered why he misses some classes.)

**Comment by tandraschko** [comment]
can you add the stacktrace?
i actually removed the whole code for this: https://github.com/apache/myfaces/commit/a511d32f2f89980bf3271d3ceb55c2352c3328fe

**Comment by christophs78** [comment]
März 25, 2021 11:13:01 AM org.apache.catalina.core.ApplicationDispatcher invoke
SEVERE: Allocate exception for servlet [FacesServlet]
java.lang.IllegalStateException: No Factories configured for this Application. This happens if the faces-initialization does not work at all - make sure that you properly include all configuration settings necessary for a basic faces application and that all the necessary libs are included. Also check the logging output of your web application and your container for any exceptions!
If you did that and find nothing, the mistake might be due to the fact that you use some special web-containers which do not support registering context-listeners via TLD files and a context listener is not setup in your web.xml.
A typical config looks like this;
<listener>
  <listener-class>org.apache.myfaces.webapp.StartupServletContextListener</listener-class>
</listener>

	at javax.faces.FactoryFinder._getFactory(FactoryFinder.java:288)
	at javax.faces.FactoryFinder.getFactory(FactoryFinder.java:209)
	at javax.faces.webapp.FacesServlet.init(FacesServlet.java:124)
	at org.apache.tomee.myfaces.TomEEWorkaroundFacesServlet.init(TomEEWorkaroundFacesServlet.java:35)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1134)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1089)
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:761)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:688)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:461)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:398)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:335)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:177)
	at org.apache.tomee.catalina.OpenEJBSecurityListener$RequestCapturer.invoke(OpenEJBSecurityListener.java:97)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by christophs78** [comment]
It´s not the same. It´s a different error.

**Comment by tandraschko** [comment]
ok, maybe a bit misconfigured
actually tomee adds myfaces startup, therefore myfaces web-fragment isnt scanned and this error occurs.
can you check that tomee-myfaces is there?

also make sure that tomee-myfaces is excluded when you add tomee-mojarra in the profile

**Comment by melloware** [comment]
This is so interesting.  We are seeing some Test failures with Mojarra that don't happen with Myfaces!

**Comment by tandraschko** [comment]
i can see some:
java.lang.NullPointerException
	at org.primefaces.extensions.integrationtests.general.converter.GeneratedDriverConverter.getAsObject(GeneratedDriverConverter.java:48)
	
looks like injection doesnt work.

**Comment by christophs78** [comment]
@melloware : Slider001Test - We run into different behaviour between Mojarra and MyFaces. So i tried to test only the things which are common for both.

@tandraschko: Is it an option to checkout this PR-branch and run it yourself against MyFaces-2.3-Next?

**Comment by christophs78** [comment]
> i can see some:
> java.lang.NullPointerException
> at org.primefaces.extensions.integrationtests.general.converter.GeneratedDriverConverter.getAsObject(GeneratedDriverConverter.java:48)
> 
> looks like injection doesnt work.

Yes. Seems to be some issue with manged @FacesConverter, TomEE and Mojarra. Any idea?
(I´m a spring-guy and have no in-depth knowledge how to modify JavaEE/JakartaEE servers.)

```java
@Named
@FacesConverter(value = "generatedDriverConverter", managed = true)
public class GeneratedDriverConverter implements Converter {

    @Inject
    private GeneratedDriverService driverService;
```

**Comment by christophs78** [comment]
Both issues left on Mojarra are caused by failing injection into managed FacesConverter.
```
Error:    AutoComplete002Test.testSuggestions:81 » NoSuchElement no such element: Unable...
Error:    CascadeSelect003Test.testBasic:55->BaseCascadeSelectTest.assertMessage:42 » NoSuchElement
```

**Comment by melloware** [comment]
@christophs78 this looks like its all passing!  Think it safe for me to Squash and Merge?

**Comment by christophs78** [comment]
> @christophs78 this looks like its all passing! Think it safe for me to Squash and Merge?

Yes :-)

(I´m also looking into sometimes wonky DataTable-global-filter-tests. PR incomming.)

**Comment by melloware** [comment]
Merged!  Great work on this.

**Pull request merged**
