### PR TITLE
Messages

### PR DESCRIPTION
**Pull request by christophs78**

### CODE REVIEW

**Comment by christophs78** [comment]
CI-Output against PF 9.0-Snapshot:
```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   InputMask003Test.testOptionalWithExtension:94 expected: <(123) 456-7890 x12345> but was: <>
[ERROR]   InputMask003Test.testOptionalWithoutExtension:77 expected: <(123) 456-7890> but was: <>
[ERROR]   InputText001Test.test:41->assertConfiguration:48 expected: <true> but was: <false>
[ERROR] Errors: 
[ERROR]   InputMask001Test.testAjaxChangeEvent:39 » Timeout Timeout while waiting for AJ...
[ERROR]   InputMask001Test.testAutoClearFalse:55 » Timeout Timeout while waiting for AJA...
[ERROR]   InputMask001Test.testServerSideValidation:71 » Timeout Timeout while waiting f...
[ERROR]   InputMask001Test.testWidgetGetSet:93->assertConfiguration:101 » JSON JSONObjec...
[INFO] 
[ERROR] Tests run: 61, Failures: 3, Errors: 4, Skipped: 0
```

Probably we need to make some changes...

**Comment by melloware** [comment]
Yep InputMask is a new component so I had planned on testing and fixing once we upgraded to 9.0. I will fix those tests.

**Comment by melloware** [comment]
I fixed the InputMask tests if you want to resync your branch.

**Comment by melloware** [comment]
OK I got all the InputMask and InputText tests updated for 9.0 and all passing. Now the only failure we are getting is on Chrome.
```
[ERROR]   Dialog001Test.testBasicCancel:95->assertConfiguration:122->AbstractPrimePageTest.assertNoJavascriptErrors:170 Javascript errors were detected in the browser console.
[[2020-09-03T11:23:44+0000] [SEVERE] http://localhost:8341/javax.faces.resource/core.js.xhtml?ln=primefaces&v=9.0-SNAPSHOT&v=9.0-SNAPSHOT 3656:20 Uncaught TypeError: Cannot read property 'attr' of undefined] ==> expected: <true> but was: <false>
[ERROR]   Dialog001Test.testBasicOk:62->assertConfiguration:122->AbstractPrimePageTest.assertNoJavascriptErrors:170 Javascript errors were detected in the browser console.
[[2020-09-03T11:23:41+0000] [SEVERE] http://localhost:8341/javax.faces.resource/core.js.xhtml;jsessionid=E953DD0536299ECDD2A72430393D0E9F?ln=primefaces&v=9.0-SNAPSHOT&v=9.0-SNAPSHOT 3656:20 Uncaught TypeError: Cannot read property 'attr' of undefined, [2020-09-03T11:23:42+0000] [SEVERE] http://localhost:8341/javax.faces.resource/core.js.xhtml;jsessionid=E953DD0536299ECDD2A72430393D0E9F?ln=primefaces&v=9.0-SNAPSHOT&v=9.0-SNAPSHOT 3656:20 Uncaught TypeError: Cannot read property 'attr' of undefined] ==> expected: <true> but was: <false>
```

**Comment by christophs78** [comment]
This PR should be ready.
But i have no solution for  the Dialog-issue on Chrome yet. On my notebook this test passes for 9.0-SNAPSHOT on Chrome. Still have to think what may be wrong...

**Pull request merged**
