### PR TITLE
DataTable: cleanup sorting

### PR DESCRIPTION
**Pull request by christophs78**
adapt to https://github.com/primefaces/primefaces/pull/6390

### CODE REVIEW

**Comment by melloware** [comment]
The new Sorting changes have been merged today in PF core.  So I think its safe to continue with this PR.

**Comment by melloware** [comment]
Also there are some other changes you will need to make to make this work and remove some of the @Disabled tests you have.  Thanks!

**Comment by christophs78** [comment]
@Rapster : Can you have a look at DataTable002Test.testLazyFilter? (see Checks-tab of this PR)
There may be a regression regarding the combination of sort and filter together with LazyDataModel.

**Comment by melloware** [comment]
Thanks I am going to merge this since I believe all of your tests are correct its the new PF code that is the issue.

**Pull request merged**
