### PR TITLE
#87 run integration-tests additional on MacOS + Safari

### PR DESCRIPTION
**Pull request by christophs78**

### CODE REVIEW

**Comment by christophs78** [comment]
@sqores - Finally got integration tests working on Safari. Had to disable parallel test-execution. But looks like we have a couple of PF-features that do not work on Safari.

```
[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    Chips001Test.testBasic:42 expected: <Defect
Feature> but was: <DefectFeature>
Error:    Chips002Test.testBasic:42 expected: <Defect
Feature> but was: <DefectFeature>
Error:    Chips003Test.testUnique:42 expected: <One
Two> but was: <OneTwo>
Error:    Chips004Test.testToggleEditor:80 expected: <Excel
Outlook
Word> but was: <ExcelOutlookWord>
Error:    DataTable001Test.testBasicAndPaginator:75 expected: <Name> but was: <NameFilter by Name>
Error:    DataTable001Test.testFilter:154->AbstractDataTableTest.assertRows:17->AbstractDataTableTest.assertRows:22 expected: <2> but was: <3>
Error:    DataTable001Test.testSortSingle:114->AbstractDataTableTest.assertRows:17->AbstractDataTableTest.assertRows:28 expected: <2> but was: <1>
Error:    DataTable002Test.testLazyFilter:149 expected: <Language 8> but was: <Language 1>
Error:    DataTable002Test.testLazySortSingle:107 expected: <Language 10> but was: <Language 2>
Error:    DataTable007Test.testFilterAndEditRow_1442:147 expected: <abc> but was: <JavaScript>
Error:    DataTable008Test.testFilterIssue_5481:71->AbstractDataTableTest.assertRows:17->AbstractDataTableTest.assertRows:28 expected: <5> but was: <4>
Error:    DataTable014Test.testStickyHeader:67 expected: <500> but was: <0>
Error:    DataTable015Test.multiViewStateSortFilter:56->AbstractDataTableTest.assertRows:17->AbstractDataTableTest.assertRows:22 expected: <2> but was: <3>
Error:    DatePicker001Test.testBasic:54 expected: <true> but was: <false>
Error:    DatePicker001Test.testHighlight:112 expected: <true> but was: <false>
Error:    DatePicker001Test.testSelectDate:81 expected: <1978-03-25> but was: <2021-02-25>
Error:    DatePicker004Test.testDateAndTimeWithHours:85 expected: <true> but was: <false>
Error:    DatePicker004Test.testDateAndTimeWithSeconds:51 expected: <true> but was: <false>
Error:    InputText002Test.testFilledField:72 expected: <true> but was: <false>
Error:    Password002Test.testFeedbackGood:95 expected: <Good> but was: < Good>
Error:    Password002Test.testFeedbackHide:61 expected: <none> but was: <block>
Error:    Password002Test.testFeedbackShow:44 expected: <Please enter a password> but was: < Please enter a password>
Error:    Password002Test.testFeedbackStrong:112 expected: <Strong> but was: < Strong>
Error:    Password002Test.testFeedbackWeak:78 expected: <Weak> but was: < Weak>
Error:    Password003Test.testFeedbackGood:78 expected: <Orta seviye> but was: < Orta seviye>
Error:    Password003Test.testFeedbackStrong:95 expected: <Güçlü> but was: < Güçlü>
Error:    Password003Test.testFeedbackWeak:61 expected: <Zayıf> but was: < Zayıf>
Error:    Password003Test.testLocalizationPrompt:44 expected: <Lütfen şifre giriniz> but was: < Lütfen şifre giriniz>
Error:  Errors: 
Error:    Chips004Test.testClipboardPaste:55 NullPointer
Error:    ClientWindow001Test.testBasic:52 » ClassCast class org.openqa.selenium.safari....
Error:    ClientWindow001Test.testRenderedUrls:70 » ClassCast class org.openqa.selenium....
Error:    DataTable009Test.testFilterIssue1390:47 NullPointer
Error:    DataTable012Test.testFieldWithDefault:83 » NoSuchElement No value present
Error:    DatePicker006Test.testSqlDateMinMax:48 NullPointer
Error:    Schedule001Test.testEventSelect:71 » NoSuchElement 
For documentation on this ...
[INFO] 
Error:  Tests run: 181, Failures: 28, Errors: 7, Skipped: 2
```

**Comment by melloware** [comment]
OK interesting. I have a MacOS at home maybe this weekend I will try and get everything working locally.  

@jepsar Is there any way you can help us here and run it on MacOS?  We are trying to get the Safari driver working to get our tests running under safari but some of these errors look weird.

**Comment by jepsar** [comment]
Sure, I'll have a look. I also still need to create a test for the date picker meta model.

**Comment by jepsar** [comment]
I'm still on macOS 10.15.6 (I don't want to upgrade as I'm expecting a new MacBook to arrive any moment), not sure if that will be a problem.

**Comment by melloware** [comment]
> I'm still on macOS 10.15.6 (I don't want to upgrade as I'm expecting a new MacBook to arrive any moment), not sure if that will be a problem.

I don't think that will be a problem as long as the Safari Selenium Driver works it should be OK.

**Comment by christophs78** [comment]
IMO this PR is essentially ready for review.
We may remove 'headless,safari,theme-saga' temporary from our matrix in build.yaml until PF-Safari-issues are fixed.

**Comment by melloware** [comment]
OK lets let it build successfully and I will squash and merge it.

**Comment by melloware** [comment]
So does this switch our tests to run on Mac only and not on Ubuntu?  I am ok with that just asking.

**Comment by christophs78** [comment]
Yes we run our build on MacOS instead of Ubuntu. Looks like we have to select on platform. Did not find a way to say we run Chrome and Firefox-tests on Ubuntu and Safari-tests on MacOS.

**Comment by christophs78** [comment]
Build is green - we "only" need to active safari-profile after we fixed PF-Safari-issues.

**Pull request merged**
