### PR TITLE
Core-Ajax: scroll-position

### PR DESCRIPTION
**Pull request by christophs78**
Integration-test for https://github.com/primefaces/primefaces/issues/6700

### CODE REVIEW

**Comment by melloware** [comment]
I am wondering if the timing issue is because of executing JS from the server side.

PrimeFaces.current().focus("form:inputtext");

So even though our Guard is saying the page is ready that execute focus has run yet so its not focused?

**Comment by christophs78** [comment]
> I am wondering if the timing issue is because of executing JS from the server side.
> 
> PrimeFaces.current().focus("form:inputtext");
> 
> So even though our Guard is saying the page is ready that execute focus has not run yet so its not focused?

Yes, i think so too. Do you have a solution for this?
Cheap (but not ideal) work-around my be to add something like `PrimeSelenium#wait(int milliseconds)`.

**Comment by melloware** [comment]
Let me think on this if there is any way to tell the AJAX call is truly finished all of its work. Maybe @tandraschko has some thoughts.

**Comment by melloware** [comment]
@christophs78 I just made this fix to PF Selenium:

https://github.com/primefaces-extensions/primefaces-selenium/commit/1fb99192d2de3a29afdcf73e25fa84b652aa2537

Studiying the code I think the AJAX queue will only be emptied after all current scripts have finished running.  Can you try this and remove your timeout to see if it fixes it?

**Comment by christophs78** [comment]
I´m sorry. It does not fix the timing issue.

**Comment by melloware** [comment]
I am going to merge this and see if I can debug it.

**Comment by melloware** [comment]
OK so I can't make it happen locally it only happens on GitHub.  This makes me think there is some weird slowness with MacOS or something?  I do notice it seems like the builds are slower on MacOS than they were on Ubuntu.  Can you make it happen locally?

Maybe @jepsar Can try this test on MacOS with and without the `sleep` and see if he can reproduce it locally.

**Comment by tandraschko** [comment]
Could be that our guard finish to early, yep. Would need to check this in detail.

**Comment by christophs78** [comment]
It is sometimes reproduceable on my windows-dev-notebook. It works when i only run this one test. But it sometimes fails when i run all tests with parallel execution. Under this high load timing is a bit different and sometimes this test fails.

**Comment by melloware** [comment]
OK let me dig a little further.

**Comment by melloware** [comment]
OK figured it out.  It has nothing to do with our selenium code that is all fine.  It is because we are calling `Primefaces.focus()` which has a `setTimeout` to run async after 50 milliseconds.
```javascript
focus: function(id, context) {
            var selector = ':not(:submit):not(:button):input:visible:enabled[name]';

            setTimeout(function() {
                if(id) {
                    var jq = $(PrimeFaces.escapeClientId(id));

                    if(jq.is(selector)) {
                        jq.trigger('focus');
                    }
                    else {
                        var firstElement = jq.find(selector).eq(0);
                        PrimeFaces.focusElement(firstElement);
                    }
                }
                else if(context) {
                    var firstElement = $(PrimeFaces.escapeClientId(context)).find(selector).eq(0);
                    PrimeFaces.focusElement(firstElement);
                }
                else {
                    var elements = $(selector),
                    firstElement = elements.eq(0);
                    PrimeFaces.focusElement(firstElement);
                }
            }, 50);

            // remember that a custom focus has been rendered
            // this avoids to retain the last focus after ajax update
            PrimeFaces.customFocus = true;
        }
```

So our AJAX completes and calls this which is why your `Thread.sleep()` works  and why it intermittenly works becuase 50ms is fast and my machine must be fast enough to never catch this.

**Comment by melloware** [comment]
OK I found a better fix and it works!
```java
// PrimeFaces.focus() has a 50ms setTimeout() so we need to delay here
PrimeSelenium.waitGui().until(PrimeExpectedConditions.visibleInViewport(page.inputtext.getInput()));
```

**Comment by christophs78** [comment]
Perfect solution!

**Pull request merged**
