### PR TITLE
Enable CSP

### PR DESCRIPTION
**Pull request by christophs78**
IMO we should enable CSP for our integration tests. When the tests work with CSP enabled they should work with CSP disabled too.

### CODE REVIEW

**Comment by christophs78** [comment]
Seems like we have some issue with `org.primefaces.extensions.selenium.internal.Guard#http` together with CSP. 
Always results in `org.openqa.selenium.TimeoutException`.
`org.primefaces.extensions.selenium.internal.Guard#ajax` does not seem to have this issue.
Maybe it´s is some way related to `pfselenium.submitting === false`....

The issue always happens when we do something like `page.button.click();` in our integration-tests.

@melloware , @tandraschko

**Comment by christophs78** [comment]
Hm. This must be some other root cause....
grafik
We don´t get onclick with CSP enabled.

**Comment by christophs78** [comment]
With CSP=true there is no onclick-attribute. Instead:
grafik

**Comment by tandraschko** [comment]
Yep
No that easy with CSP

**Comment by melloware** [comment]
@christophs78 Yes I tried this a couple of months ago and couldn't figure out an easy way to make it work.  So one thing I thought of is if `PrimeFaces.register` added each component and event to a Map in JavaScript and then we could query it with `PrimeFaces.isRegistered('form.button', 'onclick');` or something like that in the Selenium code.

**Comment by christophs78** [comment]
> 
> 
> @christophs78 Yes I tried this a couple of months ago and couldn't figure out an easy way to make it work. So one thing I thought of is if `PrimeFaces.register` added each component and event to a Map in JavaScript and then we could query it with `PrimeFaces.isRegistered('form.button', 'onclick');` or something like that in the Selenium code.

Thought of this too. There does not seem to be a good way to get already bound events via jQuery. (jQuery thinks this is internal stuff it does not want to expose.)
This would eat a bit of (client-)memory but probably it´s not significant.

**Comment by melloware** [comment]
Yep I also ran into this wall there is no easy way to get Jquery registered events.  So that is how I landed on the Map but you are right it could take a little bit of client memory but as long as we are storing strings only it should be relatively small?

**Comment by christophs78** [comment]
Would be ideal to run integration-tests once with CSP=false and once with CSP=true.

**Comment by melloware** [comment]
> Would be ideal to run integration-tests once with CSP=false and once with CSP=true.

Or at least with a profile switch so we can add a GitHub Actions profile that runs with CSP=true while all the others run CSP=false.

**Comment by tandraschko** [comment]
im still not sure about this in general. Your current solution is with a PhaseListener, right?
This only works because we run in the same JVM - so therefore the current solution will never work if you use PFSelenium with a remote host/adress.
Therefore we should think about a plugin mechanism in PF or something, so really we can hook in our custom script with PFSelenium on the client side, nothing server side.

**Comment by melloware** [comment]
@tandraschko not sure the best way to allow plugging in without running into the timing issues that @christophs78 has mentioned with MOVE_TO_BOTTOM and without.

**Comment by christophs78** [comment]
Added a new PF Selenium - PR which ensures nothing breaks for non-CSP - remote - scenarios.

Overall it seems to be complicated. We need to inject our PF Selenium - JS after core(.csp).js and before PrimeFaces.csp.register get´s called first time. Even with a PF plug-in mechanism you have to inject pfselenium.core.csp.js in all your XHTML-pages at the right place. So you have to package it somehow into your WAR.
Personally i invested way more time into this than originally expected. At least we can do our integration tests now with and without CSP enabled after this PR is merged.

grafik

**Comment by melloware** [comment]
I agree with you for now this lets the Integration test suite test CSP without needing any changes on PF core. So we can always revisit in the future if we want to make it work for remote execution.

**Review by melloware — APPROVED** [review]

**Pull request merged**
